
stages:
  - check
  - build
  - consolidate
  - release

do_trigger:
  stage: check
  script:
    - echo "Starting"
  rules:
    - changes:
      - "*/*.kicad_sch"
      - "*/*.kicad_pcb"
      - ".gitlab-ci.yml"
      - "Makefile"
      - "*.kiplot.yaml"
      when: always

.build_step:
  image: setsoft/kicad_auto:ki6
  stage: build
  rules:
    - changes:
      - "*/*.kicad_sch"
      - "*/*.kicad_pcb"
      - ".gitlab-ci.yml"
      - "Makefile"
      - "*.kiplot.yaml"
      when: on_success

fabrication:
  extends: .build_step
  script:
    - "kiplot -d Fabrication -s run_erc,update_xml print_front print_bottom gerbers excellon_drill gerber_drills position"
  artifacts:
    expire_in: 1 day
    paths:
      - Fabrication/

assembly:
  extends: .build_step
  script:
    - "kiplot -d Assembly -s run_erc,update_xml run_drc print_front print_bottom position interactive_bom bom_html bom_csv"
  artifacts:
    expire_in: 1 day
    paths:
      - Assembly/

documentation:
  extends: .build_step
  script:
    - "kiplot -d Documentation print_sch interactive_bom bom_html bom_csv print_front print_bottom position"
  artifacts:
    expire_in: 1 day
    paths:
      - Documentation/

do_join:
  stage: consolidate
  script: echo Finished
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - Fabrication/
      - Assembly/
      - Documentation/
  rules:
    - changes:
      - "*/*.kicad_sch"
      - "*/*.kicad_pcb"
      - ".gitlab-ci.yml"
      - "*/Makefile"
      - "*.kiplot.yaml"
      when: on_success

do_release:
  stage: release
  image: registry.gitlab.com/gitlab-automation-toolkit/gitlab-auto-release
  script:
    - gitlab_auto_release --changelog CHANGELOG.md --artifacts do_join
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success

