M48
; DRILL file {KiCad (6.0.7-1)-1} date 2022 September 24, Saturday 17:28:44
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-24T17:28:44+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X3.0732Y-0.2126
X3.2732Y-0.1726
X3.2732Y-0.2526
T2
X0.6496Y-0.3091
X2.0669Y-0.3091
T0
M30
